### PR TITLE
nullptr check

### PR DESCRIPTION
**Pull request by fatchat**

### CODE REVIEW

**Comment by fatchat** [comment]
@Abhishek-N the test results are not going to codecov... maybe because we renamed the github org and now the urls are different? could you have a look please

**Comment by fatchat** [comment]
@Ishankoradia the change is so small i could force-merge it, but i was wondering how we have not seen this before

no schedule => manual deployment, of which we have plenty

**Comment by Ishankoradia** [comment]
Yes you are right , we missed it. How come we didn't catch the error or see it before ? It must be throwing a key error right.

**Comment by fatchat** [comment]
@Abhishek-N fixed it, just had to go to app.codecov.io and add the new organization

**Pull request merged**
